# Generated by Django 5.2.8 on 2025-11-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Amigable')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción Corta (Catálogo)')),
                ('descripcion_larga', models.TextField(blank=True, verbose_name='Descripción Larga (Detalle)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0, verbose_name='Inventario')),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=255, verbose_name='Ruta o Nombre de Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('nombre',),
            },
        ),
    ]
